name: 02 - Workflow events

on: 
  #push:
  #pull_request:
  #schedule:
  #  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the Trigger
        run: |
          echo "Hello !"
          echo "I have been triggered by ${{ github.event_name }} event"
        shell: bash

      - name: Debug GitHub Context
        run: |
          echo "Debugging all GitHub context variables:"
          echo "${{ toJSON(github) }}"
        shell: bash
