name: 04 - Using Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prtint the current directory
        run: ls
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci

        
    #0. checkout the code
    #1. Install deps of react app
    #2. Execute automated tests