name: 05 -1- Event Filters - Activity Types
on: 
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
jobs:
 echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Runnint whenever a PR is opened or synchronized AND Base branch is main"

    
