name: 06 - Context
run-name: 06 - Context | DEBUG - ${{ inputs.debug }}
on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
env:
    MY_WORKFLOW_VAR: "workflow variable"      
    MY_OVERWRITTEN_VAR: "job variable"          
jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job variable"
            MY_OVERWRITTEN_VAR: "job MY_OVERWRITTEN_VAR"
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{github.event_name}} "
                echo "Ref: ${{github.Ref}} "
                echo "SHA: ${{github.SHA}} "
                echo "Actor: ${{github.actor}} "
                echo "Repository: ${{github.repository}} "
                echo "Repository Owner: ${{github.repository_owner}} "
                echo "Workflow: ${{github.workflow}} "
                echo "Action: ${{github.action}} "
                echo "Event Path: ${{github.event_path}} "
                echo "Workspace: ${{github.workspace}} "
                echo "Run number ${{github.run_number}} "
            - name: Retreive Variable
              run: |
                echo "Variable: ${{vars.MY_VAR}}"
            - name: Print Env Variables
              env:
                MY_OVERWRITTEN_VAR: "step MY_OVERWRITTEN_VAR"
              run: |
                echo "Workflow Variable: ${{env.MY_WORKFLOW_VAR}}"
                echo "Job Variable: ${{env.MY_JOB_VAR}}"
                echo "Overwritten Variable: ${{env.MY_OVERWRITTEN_VAR}}"
             