name: 07 - expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print-start-up"
              if: ${{ inputs.debug == 'true' }}
              run: |
                echo "Trig gered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"
            - name: "[debug] Print when triggered from main branch"
              if: ${{inputs.debug && github.ref == 'refs/heads/main'}} 
              run: echo "I was triggered from main!"
            - name: Greetings
              run: echo "Hello, World!"